"""phase2 builder template blocks + saved_blocks

Revision ID: 31491cf73aac
Revises: e9d8d05fc8fe
Create Date: 2026-06-19 08:15:50.723390
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '31491cf73aac'
down_revision: Union[str, None] = 'e9d8d05fc8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('block', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_blocks_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocks', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('blocks')

    with op.batch_alter_table('saved_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_blocks_workspace_id'))

    op.drop_table('saved_blocks')
    # ### end Alembic commands ###
