"""phase3 automations

Revision ID: 46cca800a434
Revises: 31491cf73aac
Create Date: 2026-06-19 09:03:48.198867
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46cca800a434'
down_revision: Union[str, None] = '31491cf73aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_list_id', sa.Integer(), nullable=True),
    sa.Column('sending_domain_id', sa.Integer(), nullable=True),
    sa.Column('from_name', sa.String(length=200), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sending_domain_id'], ['sending_domains.id'], ),
    sa.ForeignKeyConstraint(['trigger_list_id'], ['contact_lists.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_runs_automation_id'), ['automation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_runs_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_runs_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('automation_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_steps_automation_id'), ['automation_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automation_id', sa.Integer(), nullable=True))
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_messages_automation_id'), ['automation_id'], unique=False)
        batch_op.create_foreign_key('fk_messages_automation_id', 'automations', ['automation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_automation_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_automation_id'))
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('automation_id')

    with op.batch_alter_table('automation_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_steps_automation_id'))

    op.drop_table('automation_steps')
    with op.batch_alter_table('automation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_automation_runs_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_automation_runs_contact_id'))
        batch_op.drop_index(batch_op.f('ix_automation_runs_automation_id'))

    op.drop_table('automation_runs')
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automations_workspace_id'))

    op.drop_table('automations')
    # ### end Alembic commands ###
