"""phase4-6 esp/growth/saas

Revision ID: c249e162c831
Revises: 46cca800a434
Create Date: 2026-06-19 09:37:32.609790
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c249e162c831'
down_revision: Union[str, None] = '46cca800a434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('events', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('signup_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('sending_domain_id', sa.Integer(), nullable=True),
    sa.Column('double_optin', sa.Boolean(), nullable=False),
    sa.Column('success_message', sa.Text(), nullable=False),
    sa.Column('redirect_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['contact_lists.id'], ),
    sa.ForeignKeyConstraint(['sending_domain_id'], ['sending_domains.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signup_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signup_forms_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('sending_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('api_key', sa.Text(), nullable=False))

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('monthly_send_limit', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('monthly_send_limit')
        batch_op.drop_column('plan')

    with op.batch_alter_table('sending_domains', schema=None) as batch_op:
        batch_op.drop_column('api_key')
        batch_op.drop_column('provider')

    with op.batch_alter_table('signup_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signup_forms_workspace_id'))

    op.drop_table('signup_forms')
    with op.batch_alter_table('outbound_webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_webhooks_workspace_id'))

    op.drop_table('outbound_webhooks')
    # ### end Alembic commands ###
