"""sending_domain verify_tls

Revision ID: f3d01c668f48
Revises: c249e162c831
Create Date: 2026-06-19 13:42:46.433849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3d01c668f48'
down_revision: Union[str, None] = 'c249e162c831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sending_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_tls', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sending_domains', schema=None) as batch_op:
        batch_op.drop_column('verify_tls')

    # ### end Alembic commands ###
